# Generated by Django 4.1.3 on 2022-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_follow_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
        migrations.AddField(
            model_name='follow',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'followers'), name='unique_followers'),
        ),
    ]
