# Generated by Django 4.1.3 on 2022-12-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
